import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {SaesxProviders} from "@saesx/app/Providers";
import {getServerSession} from "next-auth";
import {authConfig} from "@saesx/lib/auth";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modals
}: {
  children: React.ReactNode
  modals: React.ReactNode
}) {
  const session = getServerSession(authConfig)

  return (
    <html lang="en">
      <body className={inter.className}>
        <SaesxProviders session={session}>
          {children}
          {modals}
        </SaesxProviders>
      </body>
    </html>
  )
}
